/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

import javax.swing.ImageIcon;
import jogomemoria.control.JogoMemoriaCtrl;
import jogomemoria.model.PecaTabuleiro;

;

/**
 *
 * @author Aluno
 */
public class JogoMemoriaPrincipal extends javax.swing.JFrame {

    private JogoMemoriaIniciante jpf = new JogoMemoriaIniciante();
    private JogoMemoriaIntermediario jpi = new JogoMemoriaIntermediario();
    private JogoMemoriaDificil jpd = new JogoMemoriaDificil();
    private JogoMemoriaCtrl controle;

    /**
     * Creates new form JogoMemoriaForm
     */
    public JogoMemoriaPrincipal() {
        initComponents();
        controle = new JogoMemoriaCtrl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sppPrincipal = new javax.swing.JSplitPane();
        pnlPrincipal = new javax.swing.JPanel();
        lblTempo = new javax.swing.JLabel();
        spnTempo = new javax.swing.JSpinner();
        btnIniciar = new javax.swing.JButton();
        cmbNivel = new javax.swing.JComboBox();
        lblNivel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        pnlIntroducao = new javax.swing.JPanel();
        lblTela1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sppPrincipal.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        lblTempo.setText("Tempo Limite:");

        btnIniciar.setText("Iniciar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        cmbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Iniciante", "Intermediário", "Difícil" }));
        cmbNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNivelActionPerformed(evt);
            }
        });

        lblNivel.setText("Nível :");

        jButton1.setText("Cancelar");
        jButton1.setMaximumSize(new java.awt.Dimension(63, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(spnTempo)
                                .addComponent(cmbNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );

        sppPrincipal.setLeftComponent(pnlPrincipal);

        pnlIntroducao.setPreferredSize(new java.awt.Dimension(868, 525));

        lblTela1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm19Tela.png"))); // NOI18N

        jLabel1.setText("Fique Feliz Aqui!!");

        javax.swing.GroupLayout pnlIntroducaoLayout = new javax.swing.GroupLayout(pnlIntroducao);
        pnlIntroducao.setLayout(pnlIntroducaoLayout);
        pnlIntroducaoLayout.setHorizontalGroup(
            pnlIntroducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIntroducaoLayout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(pnlIntroducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIntroducaoLayout.createSequentialGroup()
                        .addComponent(lblTela1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIntroducaoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(395, 395, 395))))
        );
        pnlIntroducaoLayout.setVerticalGroup(
            pnlIntroducaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlIntroducaoLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTela1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        sppPrincipal.setRightComponent(pnlIntroducao);

        getContentPane().add(sppPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        int nivelSelec = 0;
        String nivel = (String) cmbNivel.getSelectedItem();

        if (nivel.equals("Iniciante")) {
            nivelSelec = controle.FACIL;
        }
        if (((String) cmbNivel.getSelectedItem()).equals("Intermediario")) {
            nivelSelec = controle.INTERMEDIARIO;
        }
        if (nivel.equals("Dificil")) {
            nivelSelec = controle.DIFICIL;
        }
        int tempoL = (((Integer) spnTempo.getValue()).intValue());
        controle.iniciarPartida(nivelSelec, tempoL);
        mostrarTabuleiro(rootPaneCheckingEnabled);

        this.repaint();
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void cmbNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNivelActionPerformed

    }//GEN-LAST:event_cmbNivelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JogoMemoriaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JogoMemoriaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JComboBox cmbNivel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblTela1;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JPanel pnlIntroducao;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JSpinner spnTempo;
    private javax.swing.JSplitPane sppPrincipal;
    // End of variables declaration//GEN-END:variables

    public void mostrarTabuleiro(boolean inicioJogo) {

        PecaTabuleiro pctb[][] = controle.getTabuleiro();
        int idImg;

        ImageIcon imgDuvida = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm0.png"));

        if (controle.getNivelAtual() == controle.FACIL) {

            if (inicioJogo || pctb[0][0].isVirada()) {
                idImg = pctb[0][0].getIdImagem();
                ImageIcon img00 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg00()).setIcon(img00);
            } else {
                (jpf.getLblImg00()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][1].isVirada()) {
                idImg = pctb[0][1].getIdImagem();
                ImageIcon img01 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg01()).setIcon(img01);
            } else {
                (jpf.getLblImg01()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][2].isVirada()) {
                idImg = pctb[0][2].getIdImagem();
                ImageIcon img02 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg02()).setIcon(img02);
            } else {
                (jpf.getLblImg02()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][3].isVirada()) {
                idImg = pctb[0][3].getIdImagem();
                ImageIcon img03 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg03()).setIcon(img03);
            } else {
                (jpf.getLblImg03()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][0].isVirada()) {
                idImg = pctb[1][0].getIdImagem();
                ImageIcon img10 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg10()).setIcon(img10);
            } else {
                (jpf.getLblImg10()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][1].isVirada()) {
                idImg = pctb[1][1].getIdImagem();
                ImageIcon img11 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg11()).setIcon(img11);
            } else {
                (jpf.getLblImg11()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][2].isVirada()) {
                idImg = pctb[1][2].getIdImagem();
                ImageIcon img12 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg12()).setIcon(img12);
            } else {
                (jpf.getLblImg12()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][3].isVirada()) {
                idImg = pctb[1][3].getIdImagem();
                ImageIcon img13 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg13()).setIcon(img13);
            } else {
                (jpf.getLblImg13()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][0].isVirada()) {
                idImg = pctb[2][0].getIdImagem();
                ImageIcon img20 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg20()).setIcon(img20);
            } else {
                (jpf.getLblImg20()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][1].isVirada()) {
                idImg = pctb[2][1].getIdImagem();
                ImageIcon img21 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg21()).setIcon(img21);
            } else {
                (jpf.getLblImg21()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][2].isVirada()) {
                idImg = pctb[2][2].getIdImagem();
                ImageIcon img22 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg22()).setIcon(img22);
            } else {
                (jpf.getLblImg22()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][3].isVirada()) {
                idImg = pctb[2][3].getIdImagem();
                ImageIcon img23 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg23()).setIcon(img23);
            } else {
                (jpf.getLblImg23()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][0].isVirada()) {
                idImg = pctb[3][0].getIdImagem();
                ImageIcon img30 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg30()).setIcon(img30);
            } else {
                (jpf.getLblImg30()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][1].isVirada()) {
                idImg = pctb[3][1].getIdImagem();
                ImageIcon img31 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg31()).setIcon(img31);
            } else {
                (jpf.getLblImg31()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][2].isVirada()) {
                idImg = pctb[3][2].getIdImagem();
                ImageIcon img32 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg32()).setIcon(img32);
            } else {
                (jpf.getLblImg32()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][3].isVirada()) {
                idImg = pctb[3][3].getIdImagem();
                ImageIcon img33 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpf.getLblImg33()).setIcon(img33);
            } else {
                (jpf.getLblImg33()).setIcon(imgDuvida);
            }

            getSppPrincipal().setRightComponent(jpf);
            this.setSize(800, 600);
        }
        if (controle.getNivelAtual() == controle.INTERMEDIARIO) {
            
if (inicioJogo || pctb[0][0].isVirada()) {
                idImg = pctb[0][0].getIdImagem();
                ImageIcon img00 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg00()).setIcon(img00);
            } else {
                (jpi.getLblimg00()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][1].isVirada()) {
                idImg = pctb[0][1].getIdImagem();
                ImageIcon img01 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg01()).setIcon(img01);
            } else {
                (jpi.getLblimg01()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][2].isVirada()) {
                idImg = pctb[0][2].getIdImagem();
                ImageIcon img02 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg02()).setIcon(img02);
            } else {
                (jpi.getLblimg02()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][3].isVirada()) {
                idImg = pctb[0][3].getIdImagem();
                ImageIcon img03 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg03()).setIcon(img03);
            } else {
                (jpi.getLblimg03()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][4].isVirada()) {
                idImg = pctb[0][4].getIdImagem();
                ImageIcon img04 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg04()).setIcon(img04);
            } else {
                (jpi.getLblimg04()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][5].isVirada()) {
                idImg = pctb[0][5].getIdImagem();
                ImageIcon img05 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg05()).setIcon(img05);
            } else {
                (jpi.getLblimg05()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][0].isVirada()) {
                idImg = pctb[1][0].getIdImagem();
                ImageIcon img10 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg10()).setIcon(img10);
            } else {
                (jpi.getLblimg10()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][1].isVirada()) {
                idImg = pctb[1][1].getIdImagem();
                ImageIcon img11 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg11()).setIcon(img11);
            } else {
                (jpi.getLblimg11()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][2].isVirada()) {
                idImg = pctb[1][2].getIdImagem();
                ImageIcon img12 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg12()).setIcon(img12);
            } else {
                (jpi.getLblimg12()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][3].isVirada()) {
                idImg = pctb[1][3].getIdImagem();
                ImageIcon img13 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg13()).setIcon(img13);
            } else {
                (jpi.getLblimg13()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][4].isVirada()) {
                idImg = pctb[1][4].getIdImagem();
                ImageIcon img14 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg14()).setIcon(img14);
            } else {
                (jpi.getLblimg14()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][5].isVirada()) {
                idImg = pctb[1][5].getIdImagem();
                ImageIcon img15 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg15()).setIcon(img15);
            } else {
                (jpi.getLblimg15()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][0].isVirada()) {
                idImg = pctb[2][0].getIdImagem();
                ImageIcon img20 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg20()).setIcon(img20);
            } else {
                (jpi.getLblimg20()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][1].isVirada()) {
                idImg = pctb[2][1].getIdImagem();
                ImageIcon img21 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg21()).setIcon(img21);
            } else {
                (jpi.getLblimg21()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][2].isVirada()) {
                idImg = pctb[2][2].getIdImagem();
                ImageIcon img22 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg22()).setIcon(img22);
            } else {
                (jpi.getLblimg22()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][3].isVirada()) {
                idImg = pctb[2][3].getIdImagem();
                ImageIcon img23 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg23()).setIcon(img23);
            } else {
                (jpi.getLblimg23()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][4].isVirada()) {
                idImg = pctb[2][4].getIdImagem();
                ImageIcon img24 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg24()).setIcon(img24);
            } else {
                (jpi.getLblimg24()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][5].isVirada()) {
                idImg = pctb[2][5].getIdImagem();
                ImageIcon img25 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg25()).setIcon(img25);
            } else {
                (jpi.getLblimg25()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][0].isVirada()) {
                idImg = pctb[3][0].getIdImagem();
                ImageIcon img30 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg30()).setIcon(img30);
            } else {
                (jpi.getLblimg30()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][1].isVirada()) {
                idImg = pctb[3][1].getIdImagem();
                ImageIcon img31 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg31()).setIcon(img31);
            } else {
                (jpi.getLblimg31()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][2].isVirada()) {
                idImg = pctb[3][2].getIdImagem();
                ImageIcon img32 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg32()).setIcon(img32);
            } else {
                (jpi.getLblimg32()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][3].isVirada()) {
                idImg = pctb[3][3].getIdImagem();
                ImageIcon img33 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg33()).setIcon(img33);
            } else {
                (jpi.getLblimg33()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][4].isVirada()) {
                idImg = pctb[3][4].getIdImagem();
                ImageIcon img34 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg34()).setIcon(img34);
            } else {
                (jpi.getLblimg34()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][5].isVirada()) {
                idImg = pctb[3][5].getIdImagem();
                ImageIcon img35 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg35()).setIcon(img35);
            } else {
                (jpi.getLblimg35()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][0].isVirada()) {
                idImg = pctb[4][0].getIdImagem();
                ImageIcon img40 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg40()).setIcon(img40);
            } else {
                (jpi.getLblimg40()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][1].isVirada()) {
                idImg = pctb[4][1].getIdImagem();
                ImageIcon img41 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg41()).setIcon(img41);
            } else {
                (jpi.getLblimg41()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][2].isVirada()) {
                idImg = pctb[4][2].getIdImagem();
                ImageIcon img42 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg42()).setIcon(img42);
            } else {
                (jpi.getLblimg42()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][3].isVirada()) {
                idImg = pctb[4][3].getIdImagem();
                ImageIcon img43 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg43()).setIcon(img43);
            } else {
                (jpi.getLblimg43()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][4].isVirada()) {
                idImg = pctb[4][4].getIdImagem();
                ImageIcon img44 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg44()).setIcon(img44);
            } else {
                (jpi.getLblimg44()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][5].isVirada()) {
                idImg = pctb[4][5].getIdImagem();
                ImageIcon img45 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg45()).setIcon(img45);
            } else {
                (jpi.getLblimg45()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][0].isVirada()) {
                idImg = pctb[5][0].getIdImagem();
                ImageIcon img50 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg50()).setIcon(img50);
            } else {
                (jpi.getLblimg50()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][1].isVirada()) {
                idImg = pctb[5][1].getIdImagem();
                ImageIcon img51 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg51()).setIcon(img51);
            } else {
                (jpi.getLblimg51()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][2].isVirada()) {
                idImg = pctb[5][2].getIdImagem();
                ImageIcon img52 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg52()).setIcon(img52);
            } else {
                (jpi.getLblimg52()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][3].isVirada()) {
                idImg = pctb[5][3].getIdImagem();
                ImageIcon img53 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg53()).setIcon(img53);
            } else {
                (jpi.getLblimg53()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][4].isVirada()) {
                idImg = pctb[5][4].getIdImagem();
                ImageIcon img54 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpi.getLblimg54()).setIcon(img54);
            } else {
                (jpi.getLblimg54()).setIcon(imgDuvida);
            }
        }

        if (inicioJogo || pctb[5][5].isVirada()) {
            idImg = pctb[5][5].getIdImagem();
            ImageIcon img55 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
            (jpi.getLblimg55()).setIcon(img55);
        } else {
            (jpi.getLblimg55()).setIcon(imgDuvida);
            
        }
        getSppPrincipal().setRightComponent(jpi);
        this.setSize(1024, 768);

        if (controle.getNivelAtual() == controle.DIFICIL) {

            if (inicioJogo || pctb[0][0].isVirada()) {
                idImg = pctb[0][0].getIdImagem();
                ImageIcon img00 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg00()).setIcon(img00);
            } else {
                (jpd.getLblimg00()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][1].isVirada()) {
                idImg = pctb[0][1].getIdImagem();
                ImageIcon img01 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg01()).setIcon(img01);
            } else {
                (jpd.getLblimg01()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][2].isVirada()) {
                idImg = pctb[0][2].getIdImagem();
                ImageIcon img02 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg02()).setIcon(img02);
            } else {
                (jpd.getLblimg02()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][3].isVirada()) {
                idImg = pctb[0][3].getIdImagem();
                ImageIcon img03 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg03()).setIcon(img03);
            } else {
                (jpd.getLblimg03()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][4].isVirada()) {
                idImg = pctb[0][4].getIdImagem();
                ImageIcon img04 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg04()).setIcon(img04);
            } else {
                (jpd.getLblimg04()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][5].isVirada()) {
                idImg = pctb[0][5].getIdImagem();
                ImageIcon img05 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg05()).setIcon(img05);
            } else {
                (jpd.getLblimg05()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][6].isVirada()) {
                idImg = pctb[0][6].getIdImagem();
                ImageIcon img06 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg06()).setIcon(img06);
            } else {
                (jpd.getLblimg06()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][7].isVirada()) {
                idImg = pctb[0][7].getIdImagem();
                ImageIcon img07 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg07()).setIcon(img07);
            } else {
                (jpd.getLblimg07()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[0][8].isVirada()) {
                idImg = pctb[0][8].getIdImagem();
                ImageIcon img08 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg08()).setIcon(img08);
            } else {
                (jpd.getLblImg08()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][0].isVirada()) {
                idImg = pctb[1][0].getIdImagem();
                ImageIcon img10 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg10()).setIcon(img10);
            } else {
                (jpd.getLblimg10()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][1].isVirada()) {
                idImg = pctb[1][1].getIdImagem();
                ImageIcon img11 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg11()).setIcon(img11);
            } else {
                (jpd.getLblimg11()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][2].isVirada()) {
                idImg = pctb[1][2].getIdImagem();
                ImageIcon img12 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg12()).setIcon(img12);
            } else {
                (jpd.getLblimg12()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][3].isVirada()) {
                idImg = pctb[1][3].getIdImagem();
                ImageIcon img13 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg13()).setIcon(img13);
            } else {
                (jpd.getLblimg13()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][4].isVirada()) {
                idImg = pctb[1][4].getIdImagem();
                ImageIcon img14 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg14()).setIcon(img14);
            } else {
                (jpd.getLblimg14()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][5].isVirada()) {
                idImg = pctb[1][5].getIdImagem();
                ImageIcon img15 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg15()).setIcon(img15);
            } else {
                (jpd.getLblimg15()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][6].isVirada()) {
                idImg = pctb[1][6].getIdImagem();
                ImageIcon img16 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg16()).setIcon(img16);
            } else {
                (jpd.getLblimg16()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][7].isVirada()) {
                idImg = pctb[1][7].getIdImagem();
                ImageIcon img17 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg17()).setIcon(img17);
            } else {
                (jpd.getLblimg17()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[1][8].isVirada()) {
                idImg = pctb[1][8].getIdImagem();
                ImageIcon img18 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg18()).setIcon(img18);
            } else {
                (jpd.getLblImg18()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][0].isVirada()) {
                idImg = pctb[2][0].getIdImagem();
                ImageIcon img20 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg20()).setIcon(img20);
            } else {
                (jpd.getLblimg20()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][1].isVirada()) {
                idImg = pctb[2][1].getIdImagem();
                ImageIcon img21 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg21()).setIcon(img21);
            } else {
                (jpd.getLblImg21()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][2].isVirada()) {
                idImg = pctb[2][2].getIdImagem();
                ImageIcon img22 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg22()).setIcon(img22);
            } else {
                (jpd.getLblImg22()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][3].isVirada()) {
                idImg = pctb[2][3].getIdImagem();
                ImageIcon img23 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg23()).setIcon(img23);
            } else {
                (jpd.getLblimg23()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][4].isVirada()) {
                idImg = pctb[2][4].getIdImagem();
                ImageIcon img24 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblimg24()).setIcon(img24);
            } else {
                (jpd.getLblimg24()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][5].isVirada()) {
                idImg = pctb[2][5].getIdImagem();
                ImageIcon img25 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg25()).setIcon(img25);
            } else {
                (jpd.getLblImg25()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][6].isVirada()) {
                idImg = pctb[2][6].getIdImagem();
                ImageIcon img26 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg26()).setIcon(img26);
            } else {
                (jpd.getLblImg26()).setIcon(imgDuvida);
            }
            if (inicioJogo || pctb[2][7].isVirada()) {
                idImg = pctb[2][7].getIdImagem();
                ImageIcon img27 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg27()).setIcon(img27);
            } else {
                (jpd.getLblImg27()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[2][8].isVirada()) {
                idImg = pctb[2][8].getIdImagem();
                ImageIcon img28 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg28()).setIcon(img28);
            } else {
                (jpd.getLblImg28()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][0].isVirada()) {
                idImg = pctb[3][0].getIdImagem();
                ImageIcon img30 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg30()).setIcon(img30);
            } else {
                (jpd.getLblImg30()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][1].isVirada()) {
                idImg = pctb[3][1].getIdImagem();
                ImageIcon img31 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg31()).setIcon(img31);
            } else {
                (jpd.getLblImg31()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][2].isVirada()) {
                idImg = pctb[3][2].getIdImagem();
                ImageIcon img32 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLbImg32()).setIcon(img32);
            } else {
                (jpd.getLbImg32()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][3].isVirada()) {
                idImg = pctb[3][3].getIdImagem();
                ImageIcon img33 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg33()).setIcon(img33);
            } else {
                (jpd.getLblImg33()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][4].isVirada()) {
                idImg = pctb[3][4].getIdImagem();
                ImageIcon img34 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg34()).setIcon(img34);
            } else {
                (jpd.getLblImg34()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][5].isVirada()) {
                idImg = pctb[3][5].getIdImagem();
                ImageIcon img35 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg35()).setIcon(img35);
            } else {
                (jpd.getLblImg35()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[3][6].isVirada()) {
                idImg = pctb[3][6].getIdImagem();
                ImageIcon img36 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg36()).setIcon(img36);
            } else {
                (jpd.getLblImg36()).setIcon(imgDuvida);
            }
            if (inicioJogo || pctb[3][7].isVirada()) {
                idImg = pctb[3][7].getIdImagem();
                ImageIcon img37 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg37()).setIcon(img37);
            } else {
                (jpd.getLblImg37()).setIcon(imgDuvida);
            }
            if (inicioJogo || pctb[3][8].isVirada()) {
                idImg = pctb[3][8].getIdImagem();
                ImageIcon img38 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg38()).setIcon(img38);
            } else {
                (jpd.getLblImg38()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][0].isVirada()) {
                idImg = pctb[4][0].getIdImagem();
                ImageIcon img40 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg40()).setIcon(img40);
            } else {
                (jpd.getLblImg40()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][1].isVirada()) {
                idImg = pctb[4][1].getIdImagem();
                ImageIcon img41 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg41()).setIcon(img41);
            } else {
                (jpd.getLblImg41()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][2].isVirada()) {
                idImg = pctb[4][2].getIdImagem();
                ImageIcon img42 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg42()).setIcon(img42);
            } else {
                (jpd.getLblImg42()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][3].isVirada()) {
                idImg = pctb[4][3].getIdImagem();
                ImageIcon img43 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg43()).setIcon(img43);
            } else {
                (jpd.getLblImg43()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][4].isVirada()) {
                idImg = pctb[4][4].getIdImagem();
                ImageIcon img44 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg44()).setIcon(img44);
            } else {
                (jpd.getLblImg44()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][5].isVirada()) {
                idImg = pctb[4][5].getIdImagem();
                ImageIcon img45 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg45()).setIcon(img45);
            } else {
                (jpd.getLblImg45()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][6].isVirada()) {
                idImg = pctb[4][6].getIdImagem();
                ImageIcon img46 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg46()).setIcon(img46);
            } else {
                (jpd.getLblImg46()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][7].isVirada()) {
                idImg = pctb[4][7].getIdImagem();
                ImageIcon img47 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg47()).setIcon(img47);
            } else {
                (jpd.getLblImg45()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[4][8].isVirada()) {
                idImg = pctb[4][8].getIdImagem();
                ImageIcon img48 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg48()).setIcon(img48);
            } else {
                (jpd.getLblImg45()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][0].isVirada()) {
                idImg = pctb[5][0].getIdImagem();
                ImageIcon img50 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg50()).setIcon(img50);
            } else {
                (jpd.getLblImg50()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][1].isVirada()) {
                idImg = pctb[5][1].getIdImagem();
                ImageIcon img51 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg51()).setIcon(img51);
            } else {
                (jpd.getLblImg51()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][2].isVirada()) {
                idImg = pctb[5][2].getIdImagem();
                ImageIcon img52 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg52()).setIcon(img52);
            } else {
                (jpd.getLblImg52()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][3].isVirada()) {
                idImg = pctb[5][3].getIdImagem();
                ImageIcon img53 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg53()).setIcon(img53);
            } else {
                (jpd.getLblImg53()).setIcon(imgDuvida);
            }

            if (inicioJogo || pctb[5][4].isVirada()) {
                idImg = pctb[5][4].getIdImagem();
                ImageIcon img54 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg54()).setIcon(img54);
            } else {
                (jpd.getLblImg54()).setIcon(imgDuvida);
            }
        }

        if (inicioJogo || pctb[5][5].isVirada()) {
            idImg = pctb[5][5].getIdImagem();
            ImageIcon img55 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
            (jpd.getLblImg55()).setIcon(img55);
        } else {
            (jpd.getLblImg55()).setIcon(imgDuvida);
        }

        if (inicioJogo || pctb[5][6].isVirada()) {
            idImg = pctb[5][6].getIdImagem();
            ImageIcon img56 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
            (jpd.getLblImg56()).setIcon(img56);
        } else {
            (jpd.getLblImg56()).setIcon(imgDuvida);
        }

        if (inicioJogo || pctb[5][7].isVirada()) {
            idImg = pctb[5][7].getIdImagem();
            ImageIcon img57 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
            (jpd.getLblImg57()).setIcon(img57);
        } else {
            (jpd.getLblImg57()).setIcon(imgDuvida);
        }
           if (inicioJogo || pctb[5][8].isVirada()) {
                idImg = pctb[5][8].getIdImagem();
                ImageIcon img58 = new ImageIcon(getClass().getResource("/jogomemoria/gui/img/jm" + idImg + ".png"));
                (jpd.getLblImg58()).setIcon(img58);
            } else {
                (jpd.getLblImg58()).setIcon(imgDuvida);
            
        }

        getSppPrincipal().setRightComponent(jpd);
        this.setSize(1600, 980);
    }

    /**
     * @return the sppPrincipal
     */
    public javax.swing.JSplitPane getSppPrincipal() {
        return sppPrincipal;
    }

    /**
     * @param sppPrincipal the sppPrincipal to set
     */
    public void setSppPrincipal(javax.swing.JSplitPane sppPrincipal) {
        this.sppPrincipal = sppPrincipal;
    }
}
