/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jogomemoria.gui;

/**
 *
 * @author Aluno
 */
public class JogoMemoriaIntermediario2 extends javax.swing.JPanel {

    /**
     * Creates new form JogoMemoriaIntermediario2
     */
    public JogoMemoriaIntermediario2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblimg1 = new javax.swing.JLabel();
        lblimg2 = new javax.swing.JLabel();
        lblimg7 = new javax.swing.JLabel();
        lblimg3 = new javax.swing.JLabel();
        lblimg4 = new javax.swing.JLabel();
        lblimg5 = new javax.swing.JLabel();
        lblimg6 = new javax.swing.JLabel();
        lblimg8 = new javax.swing.JLabel();
        lblimg9 = new javax.swing.JLabel();
        lblimg10 = new javax.swing.JLabel();
        lblimg11 = new javax.swing.JLabel();
        lblimg12 = new javax.swing.JLabel();
        lblimg13 = new javax.swing.JLabel();
        lblimg19 = new javax.swing.JLabel();
        lblimg25 = new javax.swing.JLabel();
        lblimg31 = new javax.swing.JLabel();
        lblimg14 = new javax.swing.JLabel();
        lblimg15 = new javax.swing.JLabel();
        lblimg16 = new javax.swing.JLabel();
        lblimg17 = new javax.swing.JLabel();
        lblimg18 = new javax.swing.JLabel();
        lblimg20 = new javax.swing.JLabel();
        lblimg21 = new javax.swing.JLabel();
        lblimg22 = new javax.swing.JLabel();
        lblimg23 = new javax.swing.JLabel();
        lblimg24 = new javax.swing.JLabel();
        lblimg26 = new javax.swing.JLabel();
        lblimg27 = new javax.swing.JLabel();
        lblimg28 = new javax.swing.JLabel();
        lblimg29 = new javax.swing.JLabel();
        lblimg30 = new javax.swing.JLabel();
        lblimg32 = new javax.swing.JLabel();
        lblimg33 = new javax.swing.JLabel();
        lblimg34 = new javax.swing.JLabel();
        lblimg35 = new javax.swing.JLabel();
        lblimg36 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(690, 610));
        setLayout(new java.awt.GridLayout(6, 6));

        lblimg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg1MouseClicked(evt);
            }
        });
        add(lblimg1);

        lblimg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg2MouseClicked(evt);
            }
        });
        add(lblimg2);

        lblimg7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg7MouseClicked(evt);
            }
        });
        add(lblimg7);

        lblimg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg3MouseClicked(evt);
            }
        });
        add(lblimg3);

        lblimg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg4MouseClicked(evt);
            }
        });
        add(lblimg4);

        lblimg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg5MouseClicked(evt);
            }
        });
        add(lblimg5);

        lblimg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg6MouseClicked(evt);
            }
        });
        add(lblimg6);

        lblimg8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg8MouseClicked(evt);
            }
        });
        add(lblimg8);

        lblimg9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg9MouseClicked(evt);
            }
        });
        add(lblimg9);

        lblimg10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg10MouseClicked(evt);
            }
        });
        add(lblimg10);

        lblimg11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg11MouseClicked(evt);
            }
        });
        add(lblimg11);

        lblimg12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg12MouseClicked(evt);
            }
        });
        add(lblimg12);

        lblimg13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg13MouseClicked(evt);
            }
        });
        add(lblimg13);

        lblimg19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg19MouseClicked(evt);
            }
        });
        add(lblimg19);

        lblimg25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg25MouseClicked(evt);
            }
        });
        add(lblimg25);

        lblimg31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg31MouseClicked(evt);
            }
        });
        add(lblimg31);

        lblimg14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg14MouseClicked(evt);
            }
        });
        add(lblimg14);

        lblimg15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg15MouseClicked(evt);
            }
        });
        add(lblimg15);

        lblimg16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg16MouseClicked(evt);
            }
        });
        add(lblimg16);

        lblimg17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg17MouseClicked(evt);
            }
        });
        add(lblimg17);

        lblimg18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg18MouseClicked(evt);
            }
        });
        add(lblimg18);

        lblimg20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg20MouseClicked(evt);
            }
        });
        add(lblimg20);

        lblimg21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg21MouseClicked(evt);
            }
        });
        add(lblimg21);

        lblimg22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg22MouseClicked(evt);
            }
        });
        add(lblimg22);

        lblimg23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg23MouseClicked(evt);
            }
        });
        add(lblimg23);

        lblimg24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg24MouseClicked(evt);
            }
        });
        add(lblimg24);

        lblimg26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg26MouseClicked(evt);
            }
        });
        add(lblimg26);

        lblimg27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg27MouseClicked(evt);
            }
        });
        add(lblimg27);

        lblimg28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg28MouseClicked(evt);
            }
        });
        add(lblimg28);

        lblimg29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg29MouseClicked(evt);
            }
        });
        add(lblimg29);

        lblimg30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg30MouseClicked(evt);
            }
        });
        add(lblimg30);

        lblimg32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg32MouseClicked(evt);
            }
        });
        add(lblimg32);

        lblimg33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg33MouseClicked(evt);
            }
        });
        add(lblimg33);

        lblimg34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg34MouseClicked(evt);
            }
        });
        add(lblimg34);

        lblimg35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg35MouseClicked(evt);
            }
        });
        add(lblimg35);

        lblimg36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogomemoria/gui/img/verso.jpg"))); // NOI18N
        lblimg36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblimg36MouseClicked(evt);
            }
        });
        add(lblimg36);
    }// </editor-fold>//GEN-END:initComponents

    private void lblimg1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg1MouseClicked

    private void lblimg2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg2MouseClicked

    private void lblimg3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg3MouseClicked

    private void lblimg4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg4MouseClicked

    private void lblimg5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg5MouseClicked

    private void lblimg6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg6MouseClicked

    private void lblimg7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg7MouseClicked

    private void lblimg8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg8MouseClicked

    private void lblimg9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg9MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg9MouseClicked

    private void lblimg10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg10MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg10MouseClicked

    private void lblimg11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg11MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg11MouseClicked

    private void lblimg12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg12MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg12MouseClicked

    private void lblimg13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg13MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg13MouseClicked

    private void lblimg14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg14MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg14MouseClicked

    private void lblimg15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg15MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg15MouseClicked

    private void lblimg16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg16MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg16MouseClicked

    private void lblimg17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg17MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg17MouseClicked

    private void lblimg18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg18MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg18MouseClicked

    private void lblimg19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg19MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg19MouseClicked

    private void lblimg20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg20MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg20MouseClicked

    private void lblimg21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg21MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg21MouseClicked

    private void lblimg22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg22MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg22MouseClicked

    private void lblimg23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg23MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg23MouseClicked

    private void lblimg24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg24MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg24MouseClicked

    private void lblimg25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg25MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg25MouseClicked

    private void lblimg26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg26MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg26MouseClicked

    private void lblimg27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg27MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg27MouseClicked

    private void lblimg28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg28MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg28MouseClicked

    private void lblimg29MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg29MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg29MouseClicked

    private void lblimg30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg30MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg30MouseClicked

    private void lblimg31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg31MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg31MouseClicked

    private void lblimg32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg32MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg32MouseClicked

    private void lblimg33MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg33MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg33MouseClicked

    private void lblimg34MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg34MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg34MouseClicked

    private void lblimg35MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg35MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg35MouseClicked

    private void lblimg36MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblimg36MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblimg36MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblimg1;
    private javax.swing.JLabel lblimg10;
    private javax.swing.JLabel lblimg11;
    private javax.swing.JLabel lblimg12;
    private javax.swing.JLabel lblimg13;
    private javax.swing.JLabel lblimg14;
    private javax.swing.JLabel lblimg15;
    private javax.swing.JLabel lblimg16;
    private javax.swing.JLabel lblimg17;
    private javax.swing.JLabel lblimg18;
    private javax.swing.JLabel lblimg19;
    private javax.swing.JLabel lblimg2;
    private javax.swing.JLabel lblimg20;
    private javax.swing.JLabel lblimg21;
    private javax.swing.JLabel lblimg22;
    private javax.swing.JLabel lblimg23;
    private javax.swing.JLabel lblimg24;
    private javax.swing.JLabel lblimg25;
    private javax.swing.JLabel lblimg26;
    private javax.swing.JLabel lblimg27;
    private javax.swing.JLabel lblimg28;
    private javax.swing.JLabel lblimg29;
    private javax.swing.JLabel lblimg3;
    private javax.swing.JLabel lblimg30;
    private javax.swing.JLabel lblimg31;
    private javax.swing.JLabel lblimg32;
    private javax.swing.JLabel lblimg33;
    private javax.swing.JLabel lblimg34;
    private javax.swing.JLabel lblimg35;
    private javax.swing.JLabel lblimg36;
    private javax.swing.JLabel lblimg4;
    private javax.swing.JLabel lblimg5;
    private javax.swing.JLabel lblimg6;
    private javax.swing.JLabel lblimg7;
    private javax.swing.JLabel lblimg8;
    private javax.swing.JLabel lblimg9;
    // End of variables declaration//GEN-END:variables
}
